//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BossComing.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BossComing.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Left click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeftClick {
            get {
                return ResourceManager.GetString("LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left double click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LeftDoubleClick {
            get {
                return ResourceManager.GetString("LeftDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Middle click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MiddleClick {
            get {
                return ResourceManager.GetString("MiddleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Left mouse button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MouseModLeft {
            get {
                return ResourceManager.GetString("MouseModLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Middle mouse button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MouseModMiddle {
            get {
                return ResourceManager.GetString("MouseModMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right mouse button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MouseModRight {
            get {
                return ResourceManager.GetString("MouseModRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RightClick {
            get {
                return ResourceManager.GetString("RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Right double click に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RightDoubleClick {
            get {
                return ResourceManager.GetString("RightDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel down に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WheelDown {
            get {
                return ResourceManager.GetString("WheelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wheel up に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WheelUp {
            get {
                return ResourceManager.GetString("WheelUp", resourceCulture);
            }
        }
    }
}
